---
- name: read logfile
  slurp:
    src: "{{ logfile_path }}"
  register: logfile_text
- debug:
    var: checklist_id
- debug:
    msg: "{{ apex_url }}/{{ apex_uri }}/patching/ls_inventory/"  
- debug:
    msg: "{{ checklist_id }}"

- block:
  - name: execute 'upload DB patch lsinv' API call
    uri:
      url: "{{ apex_url }}/{{ apex_uri }}/patching/ls_inventory/"
      validate_certs: no  # should be removed after https certs becomes renewed
      method: POST
      body: "{{ logfile_text.content | b64decode | string }}"
      headers:
        Content-Type: text/plain
        ID: "{{ checklist_id }}"
    register: log_insrt_response
  rescue:
  - name: 
    delegate_to: localhost
    lineinfile:
      path: /apex/unsent_json_body/{{ ansible_hostname }}/upload_log.json
      line: '{"checklist_id": {{ checklist_id | to_json }} }, {"logfile_path": {{ logfile_path | to_json }} }'
      create: yes
