---
oracle_home: "{{ oracle_base }}/product/{{ oracle_version }}/{{ oracle_db_home }}"
oracle_user: oracle
oracle_group: oinstall
oracle_dba_group: dba

cluster_nodes: "{{ ansible_play_hosts }}"

master_node: "{{ ansible_play_hosts | sort | first }}"

# shell environment for the oracle user
ora_user_env:
  ORACLE_BASE: "{{ oracle_base }}/oracle"
  ORACLE_SID: "{{ oracle_db_name }}"
  ORACLE_UNQNAME: "{{ oracle_db_name }}"
  ORACLE_HOME: "{{ oracle_home }}"
  NLS_LANG: "American_America.UTF8"
  TMP: "/u01/app/oracle"
  TMPDIR: "/u01/app/oracle"
