---

oracle_home: "{{ oracle_base }}/product/{{ oracle_version }}/{{ oracle_db_home }}"

grid_home: "{{ install_base }}/{{ grid_version }}/grid_1"

oracle_user: oracle

oracle_tmp: /u01/tmp/{{ oracle_db_name}}

# shell environment for the oracle user
ora_user_env:
  ORACLE_BASE: "{{ oracle_base }}"
  ORACLE_SID: "{{ oracle_db_name }}"
  ORACLE_UNQNAME: "{{ oracle_db_name }}"
  ORACLE_HOME: "{{ oracle_home }}"
  NLS_LANG: "American_America.UTF8"
  PATH: "{{ oracle_home }}/bin:{{ grid_home }}/bin:{{ ansible_env.PATH }}"
  TMP: "/u01/app/oracle"
  TMPDIR: "/u01/app/oracle"

cluster_nodes: "{{ ansible_play_hosts }}"

master_node: "{{ ansible_play_hosts | sort | first }}"
