---
#Enter an Environment (LAB, DEV, UAT, TST, QA, SIT, DR, PRD)
Env1: DEV
#What Data Center is this being built in? (GVL, NCE, NCW)
DC: NCE
#What Domain is this being installed on? (CHTR, Corp, DEV, TWCCORP, TWZDMZ, UAT)
Domain: CHTR
#Backup Path
BuPath: 'H:\Backups'
#Data Path
DataPath: 'G:\Data'
#Log Path
LogPath: 'E:\Logs'
#System Path
SystemPath: 'F:\System'
#Temdb Path
TempdbPath: 'I:\'
#Enter SQL Version (2012, 2014, 2016, 2017)
SqlVersion: 2014
SSMSVersion: 'v2017'
adminaccounts: 'Administrator'
domain_admin_username: administrator
dns_domain_name: ad.getfamiliar.com
