---
- name: replace tabs for spaces as oracle checks include a space
  replace:
    path: /etc/security/limits.conf
    regexp: '\t'
    replace: '  '

- name: oracle-recommended sysctl for 11g
  sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    state: present
    ignoreerrors: yes # Ignore errors about unknown keys
  with_items:
    - { name: "kernel.shmall", value: "56102409" } 
    - { name: "kernel.shmmax", value: "270378528768" } 
    - { name: "kernel.shmmni", value: "4096" }
    - { name: "kernel.sem", value: "250 32000 100 128" } 
    - { name: "fs.file-max", value: "13631488" } 
    - { name: "fs.aio-max-nr", value: "1048576" } 
    - { name: "net.ipv4.ip_local_port_range", value: "9000 65500" } 
    - { name: "net.core.rmem_default", value: "262144" }
    - { name: "net.core.rmem_max", value: "4194304" } 
    - { name: "net.core.wmem_default", value: "262144" } 
    - { name: "net.core.wmem_max", value: "1048576" } 
  when: oracle_version | regex_replace ('^([0-9]{1,2}.[0-9]{1,}.[0-9]{1,})(.*)$','\g<1>') == "11.2.0"

- name: oracle-recommended sysctl for 12c
  sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    state: present
    ignoreerrors: yes # Ignore errors about unknown keys
  with_items:
    - { name: "kernel.shmall", value: "1073741824" }
    - { name: "kernel.shmmax", value: "4398046511104" }
    - { name: "kernel.shmmni", value: "4096" }
    - { name: "kernel.sem", value: "250 32000 100 128" }
    - { name: "fs.file-max", value: "6815744" }
    - { name: "fs.aio-max-nr", value: "1048576" }
    - { name: "net.ipv4.ip_local_port_range", value: "9000 65500" }
    - { name: "net.core.rmem_default", value: "262144" }
    - { name: "net.core.rmem_max", value: "4194304" }
    - { name: "net.core.wmem_default", value: "262144" }
    - { name: "net.core.wmem_max", value: "1048576" }
    - { name: "net.ipv4.conf.all.rp_filter", value: "2"}
    - { name: "net.ipv4.conf.default.rp_filter", value: "2"}
    - { name: "kernel.panic_on_oops", value: "1"}
  when: oracle_version | regex_replace ('^([0-9]{1,2}.[0-9]{1,}.[0-9]{1,})(.*)$','\g<1>') == "12.2.0"
  
- name: save sysctl config
  command: sysctl -p
  ignore_errors: yes 

- name: oracle-recommended PAM config
  lineinfile:
    dest: /etc/pam.d/login
    state: present
    line: "session required pam_limits.so"
    backup: yes
  when: oracle_version | regex_replace ('^([0-9]{1,2}.[0-9]{1,}.[0-9]{1,})(.*)$','\g<1>') == "11.2.0"

- name: oracle-recommended security limits for 11g
  pam_limits:
    domain: "{{ oracle_user.name }}"
    limit_type: "{{ item.type }}"
    limit_item: "{{ item.entry }}"
    value: "{{ item.setting }}"
  with_items:
    - { type: soft, entry: nproc, setting: "2047" }
    - { type: hard, entry: nproc, setting: "16384" }
    - { type: soft, entry: nofile, setting: "1024" }
    - { type: hard, entry: nofile, setting: "65536" }
    - { type: soft, entry: stack, setting: "10240" }
    - { type: hard, entry: stack, setting: "10240" }
    - { type: soft, entry: memlock, setting: unlimited }
    - { type: hard, entry: memlock, setting: unlimited }
  when: oracle_version | regex_replace ('^([0-9]{1,2}.[0-9]{1,}.[0-9]{1,})(.*)$','\g<1>') == "11.2.0"
  
- name: oracle-recommended security limits for 12c
  pam_limits:
    domain: "{{ oracle_user.name }}"
    limit_type: "{{ item.type }}"
    limit_item: "{{ item.entry }}"
    value: "{{ item.setting }}"
  with_items:
    - { type: soft, entry: nproc, setting: "2047" }
    - { type: hard, entry: nproc, setting: "16384" }
    - { type: soft, entry: nofile, setting: "2047" }
    - { type: hard, entry: nofile, setting: "65536" }
    - { type: soft, entry: stack, setting: "10240" }
    - { type: hard, entry: stack, setting: "unlimited" }
    - { type: soft, entry: memlock, setting: unlimited }
    - { type: hard, entry: memlock, setting: unlimited }
  when: oracle_version | regex_replace ('^([0-9]{1,2}.[0-9]{1,}.[0-9]{1,})(.*)$','\g<1>') == "12.2.0" or oracle_version | regex_replace ('^([0-9]{1,2}.[0-9]{1,}.[0-9]{1,})(.*)$','\g<1>') == "12.1.0"

- name: get service facts
  service_facts:

- name: disable the avahi daemon
  systemd:
    name: avahi-daemon
    enabled: no
    state: stopped
  when: ansible_facts.services['avahi-daemon.service'] is defined
