---
- name: Run Opatch Prereqs
  become_user: "{{ oracle_user }}"
  environment: "{{ ora_user_env }}"
  command: opatch prereq CheckConflictAgainstOHWithDetail -phBaseDir {{ pstage }}/{{ patch_num }}
  ignore_errors: yes
  register: opatch_prereq

- name: save opatch prereq stdout
  copy:
    dest: "{{ oracle_tmp }}/opatch_prereq.out"
    content: "{{ opatch_prereq.stdout }}"
  changed_when: False

- name: save opatch prereq stderr
  copy:
    dest: "{{ oracle_tmp }}/prereq.err"
    content: "{{ opatch_prereq.stderr }}"
  changed_when: False
  when: opatch_prereq.stderr_lines | length > 0
